import { zodResolver } from '@hookform/resolvers/zod';
import { ArrowLeft, Calculator, Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { useFieldArray, useForm, useWatch } from 'react-hook-form';
import { useNavigate, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { z } from 'zod';
import { Button } from '../design-system/Button';
import { ButtonLink } from '../design-system/ButtonLink';
import { FieldError } from '../design-system/FieldError';
import { FormField } from '../design-system/FormField';
import { Input } from '../design-system/Input';
import { Loading } from '../design-system/Loading';
import { PageHeader } from '../design-system/PageHeader';
import { SearchInput } from '../design-system/SearchInput';
import { Select } from '../design-system/Select';
import { Surface } from '../design-system/Surface';
import { Textarea } from '../design-system/Textarea';
import { api, showApiError } from '../services/api';
import type { ApiResponse, Client, Paginated, Product, Quote, QuotePayload } from '../types';
import { formatMoney } from '../utils/format';

const itemSchema = z.object({ product_id: z.number().nullable().optional(), item_name: z.string().min(1, 'Informe o item.'), item_description: z.string().nullable().optional(), quantity: z.number().positive('Quantidade maior que zero.'), unit_price: z.number().min(0, 'Preço inválido.') });
const schema = z.object({ client_id: z.number().positive('Selecione o cliente.'), status: z.enum(['draft', 'sent', 'approved', 'rejected']), discount_type: z.enum(['fixed', 'percentage']), discount_value: z.number().min(0), notes: z.string(), valid_until: z.string().min(1, 'Informe a validade.'), items: z.array(itemSchema).min(1, 'Adicione pelo menos um item.') }).refine((v) => v.discount_type !== 'percentage' || v.discount_value <= 100, { path: ['discount_value'], message: 'Máximo de 100%.' });
type FormData = z.infer<typeof schema>;
const futureDate = () => new Date(Date.now() + 15 * 86400000).toISOString().slice(0, 10);
const blank: FormData = { client_id: 0, status: 'draft', discount_type: 'fixed', discount_value: 0, notes: '', valid_until: futureDate(), items: [] };

export function QuoteFormPage() {
  const { id } = useParams(); const navigate = useNavigate(); const [clients, setClients] = useState<Client[]>([]); const [products, setProducts] = useState<Product[]>([]); const [clientSearch, setClientSearch] = useState(''); const [productSearch, setProductSearch] = useState(''); const [loading, setLoading] = useState(Boolean(id));
  const { control, register, handleSubmit, reset, formState: { errors, isSubmitting } } = useForm<FormData>({ resolver: zodResolver(schema), defaultValues: blank });
  const { fields, append, remove } = useFieldArray({ control, name: 'items' });
  const values = useWatch({ control });
  useEffect(() => { Promise.all([api.get<ApiResponse<Paginated<Client>>>('/clients', { params: { limit: 100 } }), api.get<ApiResponse<Paginated<Product>>>('/products', { params: { limit: 100, status: 'active' } })]).then(([c, p]) => { setClients(c.data.data.items); setProducts(p.data.data.items); }).catch((e) => showApiError(e)); }, []);
  useEffect(() => { if (!id) return; api.get<ApiResponse<Quote>>(`/quotes/${id}`).then((r) => { const q = r.data.data; reset({ client_id: q.client_id, status: q.status, discount_type: q.discount_type, discount_value: Number(q.discount_value), notes: q.notes ?? '', valid_until: q.valid_until.slice(0, 10), items: q.items?.map((item) => ({ product_id: item.product_id, item_name: item.item_name, item_description: item.item_description ?? '', quantity: Number(item.quantity), unit_price: Number(item.unit_price) })) ?? [] }); }).catch((e) => showApiError(e)).finally(() => setLoading(false)); }, [id, reset]);
  const subtotal = useMemo(() => (values.items ?? []).reduce((sum, item) => sum + (Number(item?.quantity) || 0) * (Number(item?.unit_price) || 0), 0), [values.items]);
  const discount = values.discount_type === 'percentage' ? subtotal * ((Number(values.discount_value) || 0) / 100) : Number(values.discount_value) || 0;
  const total = Math.max(0, subtotal - Math.min(subtotal, discount));
  const filteredClients = clients.filter((c) => `${c.name} ${c.company ?? ''}`.toLowerCase().includes(clientSearch.toLowerCase()));
  const filteredProducts = products.filter((p) => p.name.toLowerCase().includes(productSearch.toLowerCase()));
  const addProduct = (product: Product) => append({ product_id: product.id, item_name: product.name, item_description: product.description ?? '', quantity: 1, unit_price: Number(product.unit_price) });
  const submit = async (data: FormData) => { try { const payload: QuotePayload = { ...data, notes: data.notes || null }; const r = id ? await api.put<ApiResponse<Quote>>(`/quotes/${id}`, payload) : await api.post<ApiResponse<Quote>>('/quotes', payload); toast.success(id ? 'Orçamento atualizado.' : 'Orçamento criado.'); navigate(`/orcamentos/${r.data.data.id}`); } catch (e) { showApiError(e); } };
  if (loading) return <Loading label="Abrindo orçamento..." />;
  return <>
    <PageHeader eyebrow={id ? 'Edição' : 'Nova oportunidade'} title={id ? 'Editar orçamento' : 'Criar orçamento'} description="Monte uma proposta clara. Os totais serão conferidos novamente pelo servidor." action={<ButtonLink to="/orcamentos" variant="secondary"><ArrowLeft size={17} />Voltar</ButtonLink>} />
    <form onSubmit={handleSubmit(submit)} className="grid gap-5 xl:grid-cols-[1fr_340px]">
      <div className="space-y-5"><Surface as="section" className="p-5 sm:p-6"><h2 className="font-semibold text-navy">1. Cliente e condições</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><FormField className="sm:col-span-2" label="Buscar cliente"><SearchInput value={clientSearch} onChange={(e) => setClientSearch(e.target.value)} placeholder="Nome ou empresa" /></FormField><FormField label="Cliente" error={errors.client_id?.message}><Select {...register('client_id', { valueAsNumber: true })}><option value={0}>Selecione...</option>{filteredClients.map((client) => <option key={client.id} value={client.id}>{client.name}{client.company ? ` — ${client.company}` : ''}</option>)}</Select></FormField><FormField label="Validade" error={errors.valid_until?.message}><Input type="date" {...register('valid_until')} /></FormField><FormField label="Status"><Select {...register('status')}><option value="draft">Rascunho</option><option value="sent">Enviado</option><option value="approved">Aprovado</option><option value="rejected">Recusado</option></Select></FormField></div></Surface>
        <Surface as="section" className="p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="font-semibold text-navy">2. Itens da proposta</h2><p className="mt-1 text-sm text-slate-500">Escolha no catálogo ou adicione um item personalizado.</p></div><Button type="button" variant="secondary" onClick={() => append({ product_id: null, item_name: '', item_description: '', quantity: 1, unit_price: 0 })}><Plus size={17} />Item personalizado</Button></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><SearchInput placeholder="Pesquisar no catálogo" value={productSearch} onChange={(e) => setProductSearch(e.target.value)} />{productSearch && <div className="mt-2 max-h-44 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-lg">{filteredProducts.slice(0, 8).map((product) => <button type="button" key={product.id} onClick={() => { addProduct(product); setProductSearch(''); }} className="flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left hover:bg-blue-50"><span><strong className="block text-sm text-slate-700">{product.name}</strong><small className="text-slate-400">{product.type === 'service' ? 'Serviço' : 'Produto'}</small></span><span className="text-sm font-semibold text-brand-700">{formatMoney(product.unit_price)}</span></button>)}</div>}</div>
          {errors.items?.root && <FieldError className="mt-3">{errors.items.root.message}</FieldError>}<div className="mt-5 space-y-3">{fields.length === 0 && <div className="rounded-xl border border-dashed border-slate-300 px-5 py-10 text-center text-sm text-slate-400">Pesquise no catálogo ou crie um item personalizado.</div>}{fields.map((field, index) => <div className="rounded-xl border border-slate-200 p-4" key={field.id}><div className="grid gap-3 sm:grid-cols-[1fr_90px_150px_42px]"><FormField label="Item" error={errors.items?.[index]?.item_name?.message}><Input {...register(`items.${index}.item_name`)} /></FormField><FormField label="Qtd."><Input type="number" step="0.001" min="0.001" {...register(`items.${index}.quantity`, { valueAsNumber: true })} /></FormField><FormField label="Preço unitário"><Input type="number" step="0.01" min="0" {...register(`items.${index}.unit_price`, { valueAsNumber: true })} /></FormField><button type="button" className="mt-7 grid size-10 place-items-center rounded-xl text-slate-400 hover:bg-red-50 hover:text-red-600" onClick={() => remove(index)} aria-label="Remover item"><Trash2 size={17} /></button><FormField className="sm:col-span-4" label="Descrição"><Input {...register(`items.${index}.item_description`)} /></FormField></div><p className="mt-3 text-right text-sm text-slate-500">Total do item: <strong className="text-slate-800">{formatMoney((Number(values.items?.[index]?.quantity) || 0) * (Number(values.items?.[index]?.unit_price) || 0))}</strong></p></div>)}</div>
        </Surface>
        <Surface as="section" className="p-5 sm:p-6"><h2 className="font-semibold text-navy">3. Mensagem e observações</h2><Textarea className="mt-4 min-h-32 py-3" placeholder="Condições comerciais, prazo de execução, formas de pagamento..." {...register('notes')} /></Surface></div>
      <aside className="xl:sticky xl:top-24 xl:self-start"><Surface as="section" className="overflow-hidden"><div className="bg-navy p-5 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-white/10 text-orange-300"><Calculator size={20} /></span><div><h2 className="font-semibold">Resumo financeiro</h2><p className="text-xs text-blue-200">Atualizado em tempo real</p></div></div></div><div className="p-5"><div className="flex justify-between text-sm text-slate-500"><span>Subtotal</span><strong className="text-slate-800">{formatMoney(subtotal)}</strong></div><div className="mt-5 grid grid-cols-[1fr_1.2fr] gap-3"><FormField label="Desconto"><Select {...register('discount_type')}><option value="fixed">R$</option><option value="percentage">%</option></Select></FormField><FormField label="Valor" error={errors.discount_value?.message}><Input type="number" min="0" step="0.01" {...register('discount_value', { valueAsNumber: true })} /></FormField></div><div className="mt-4 flex justify-between border-b border-slate-100 pb-5 text-sm text-slate-500"><span>Desconto aplicado</span><strong className="text-red-600">- {formatMoney(Math.min(subtotal, discount))}</strong></div><div className="flex items-end justify-between py-6"><span className="font-semibold text-navy">Total</span><strong className="text-2xl text-brand-700">{formatMoney(total)}</strong></div><Button variant="primary" className="w-full py-3" disabled={isSubmitting}><Save size={18} />{isSubmitting ? 'Salvando...' : id ? 'Salvar alterações' : 'Criar orçamento'}</Button><p className="mt-3 text-center text-xs leading-5 text-slate-400">Os valores serão recalculados e validados antes de salvar.</p></div></Surface></aside>
    </form>
  </>;
}
